### ISSUE TITLE
Error running filter pandoc-plantuml: Filter returned error status 1

### ISSUE THREAD

**Issue by damgot** [timofurrer/pandoc-plantuml-filter#5]
Hello, 

I tried to run your script with pandoc and I have the following error : 

PS C:\Users\xxx\AppData\Local\Programs\Python\Python37-32> pandoc "p:\<path-to-md-file.md>" -o "p:\<path-to-pdf-file.pdf>" --filter pandoc-plantuml
Traceback (most recent call last):
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\Scripts\pandoc-plantuml.exe\__main__.py", line 9, in <module>
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\pandoc_plantuml_filter.py", line 46, in main
    toJSONFilter(plantuml)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 132, in toJSONFilter
    toJSONFilters([action])
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 166, in toJSONFilters
    sys.stdout.write(applyJSONFilters(actions, source, format))
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 197, in applyJSONFilters
    altered = walk(altered, action, format, meta)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 124, in walk
    x[k] = walk(x[k], action, format, meta)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages\pandoc_plantuml_filter.py", line 39, in plantuml
    subprocess.check_call(PLANTUML_BIN.split() + ["-t" + filetype, src])
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "c:\users\xxx\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Error running filter pandoc-plantuml:
Filter returned error status 1

Can you help me ?

Many thanks and best regards

**Comment by timofurrer** [comment]
It can't find your plantuml binary - it's not called `plantuml` and/or is not in your `$PATH`. 

Specify the path to the plantuml binary via the `PLANTUML_BIN` environment variable!
