### ISSUE TITLE
Permission issue when trying to run the filter

### ISSUE THREAD

**Issue by rendercraft** [timofurrer/pandoc-plantuml-filter#6]
pandoc foo.md -o foo.pdf --filter pandoc-plantuml
Traceback (most recent call last):
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\1000087376\AppData\Local\Programs\Python\Python37-32\Scripts\pandoc-plantuml.exe\__main__.py", line 9, in <module>
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\site-packages\pandoc_plantuml_filter.py", line 47, in main
    toJSONFilter(plantuml)
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 132, in toJSONFilter
    toJSONFilters([action])
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 166, in toJSONFilters
    sys.stdout.write(applyJSONFilters(actions, source, format))
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 197, in applyJSONFilters
    altered = walk(altered, action, format, meta)
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 124, in walk
    x[k] = walk(x[k], action, format, meta)
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\site-packages\pandocfilters.py", line 111, in walk
    item['c'] if 'c' in item else None, format, meta)
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\site-packages\pandoc_plantuml_filter.py", line 40, in plantuml
    PLANTUML_BIN, "-t" + filetype, src])
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\subprocess.py", line 336, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\subprocess.py", line 317, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "c:\users\1000087376\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access is denied
Error running filter pandoc-plantuml:
Filter returned error status 1

**Comment by rendercraft** [comment]
Hi! Do you have an idea of what could be causing the above?

**Comment by timofurrer** [comment]
Well, I don't know about Windows, but I assume (like the error said) that you don't have permissions to execute the `PLANTUML_BIN` binary. 
Can you try to execute it manually from the cmd line?

**Comment by rendercraft** [comment]
I'm able to execute the plantuml binary fine on the cmd line...I'll try elevated privileges.

**Comment by rendercraft** [comment]
I'd like to close this issue, as I was able to run your filter fine on my mac
